version: '3.8'

services:
  app:
    build: .
    container_name: openclaw-whatsapp-bot
    restart: always
    volumes:
      - ./auth_info_baileys:/usr/src/app/auth_info_baileys
    env_file:
      - .env
    tty: true # Importante para ver o QR Code no terminal
    stdin_open: true # Importante para interatividade se necess√°rio
